set DIR Ex
set SYM_LINK Gx
set SOCKET Fx
set PIPE dx
set EXE Cx
set BLOCK_SP Dx
set CHAR_SP Dx
set EXE_SUID hb
set EXE_GUID ad
set DIR_STICKY Ex
set DIR_WO_STICKY Ex
set -x LSCOLORS "$DIR$SYM_LINK$SOCKET$PIPE$EXE$BLOCK_SP$CHAR_SP$EXE_SUID$EXE_GUID$DIR_STICKY$DIR_WO_STICKY"
