# Bash Shell Profile

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Get the operating system. Possible values:
#  * GNU/Linux = Linux
#  * Cygwin = Windows Cygwin prompts
#  * Darwin = MacOS
OPSYS=$(uname -o 2>/dev/null || uname -s)

# History settings. Don't put duplicate lines and ignore successive entries in history list.
export HISTCONTROL=ignoredups
export HISTCONTROL=ignoreboth

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# Set up environment variables
EDITOR=vim
LESS="-M -I -R"; export LESS
# Highlight grep matches
GREP_OPTIONS='--color=auto'; export GREP_OPTIONS

# MacOS specific settings
if [ $OPSYS == "Darwin" ]; then
    # If homebrew is installed and the bash completion package is present, source it.
    if [ -x /usr/local/bin/brew ] && [ -f $(brew --prefix)/etc/bash_completion ]; then
        . $(brew --prefix)/etc/bash_completion
    fi
fi

if [ $OPSYS == "Cygwin" ]; then
    # In Windows, these variables are already defined so I we should unset them in Cygwin.
    unset TMP
    unset TEMP
fi

BASH_PROFILE_DIR="$(cd "$(dirname $(realpath "${BASH_SOURCE[0]}"))" && pwd)"

# Source files in conf.d directory
for file in "${BASH_PROFILE_DIR}/conf.d/"*.bash; do
    [[ -f "${file}" ]] || continue
    source "${file}"
done

# Source files in functions directory
for file in "${BASH_PROFILE_DIR}/functions/"*.bash; do
    [[ -f "${file}" ]] || continue
    source "${file}"
done
