# Bash Shell Profile

# Set up environment variables
EDITOR=vim
LESS="-M -I -R"; export LESS
# Highlight grep matches
GREP_OPTIONS='--color=auto'; export GREP_OPTIONS

# Check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# History settings. Don't put duplicate lines and commands that begin with a space (e.g. ignoredupes and ignorespace).
export HISTCONTROL=ignoreboth

BASH_PROFILE_DIR="$(cd "$(dirname $(realpath "${BASH_SOURCE[0]}"))" && pwd)"

# Source files in conf.d directory
for file in "${BASH_PROFILE_DIR}/conf.d/"*.bash; do
    [[ -f "${file}" ]] || continue
    source "${file}"
done

# Source files in functions directory
for file in "${BASH_PROFILE_DIR}/functions/"*.bash; do
    [[ -f "${file}" ]] || continue
    source "${file}"
done
